#! bin/bash

## ROTTE
curl -X GET "http://localhost:1996" | jq
curl -X GET "http://localhost:1996/about" | jq
curl -X GET "http://localhost:1996/status" | jq
curl -X GET "http://localhost:1996/prodotti" | jq
curl -X GET "http://localhost:1996/prodotti/1" | jq